### ISSUE TITLE
Feature request, #to_h on response objects

### ISSUE THREAD

**Issue by bbozo** [braintree/braintree_ruby#108] opened 2016-01-23 17:58 UTC
Hello dear Braintree team,

could you please add a `#to_h` (to hash) method to your response objects which would return the attributes hash of the object? It would allow us to serialize responses and do a bunch of other useful stuff,

some examples would be:

1. serialize & store responses in a database column, such as PG's JSON column
2. send the objects as a parameter to a background worker (currently I send the transaction IDs to sidekiq and then perform a find api call for each transaction when I update statuses instead of simply sending the transaction objects to the queue)

**Comment by crookedneighbor** [comment] 2016-01-25 17:23
Closing this as a duplicate of https://github.com/braintree/braintree_ruby/issues/92

This is not currently on our roadmap, but the [workaround suggested in this comment](https://github.com/braintree/braintree_ruby/issues/92#issuecomment-147824809) should work.

**Closed by crookedneighbor** 2016-01-25 17:23 UTC
