### ISSUE TITLE
Transaction response (or the documentation for it) needs love

### ISSUE THREAD

**Issue by dan-ding** [braintree/braintree_ruby#134] opened 2016-12-17 02:10 UTC
According to:
https://developers.braintreepayments.com/reference/response/transaction/ruby#successful-result

It seems that:
Transaction.find
is a bit of an exception to the response according to:
https://developers.braintreepayments.com/reference/request/transaction/find/ruby

Even though the latter of the above references says to look at the former for more details about the response.

**Comment by dan-ding** [comment] 2016-12-17 02:13
Personally, I'd prefer that `find `returns something and `find!` raises an error.

**Comment by EvanHahn** [comment] 2017-04-11 21:23
So sorry to let this issue linger for months!

It sounds to us like you're asking for two things: (1) you feel that `find` shouldn't raise (2) our docs around `find` are wrong.

1. `find` raises an error by design. It *does* seem inconsistent at first—why do many of the methods return a result object but `find` raises an error?

   Let's compare it to `Transaction.sale`. A developer can write perfectly correct code and `Transaction.sale` can still fail; the customer might not have enough money in their account, for example. If we play the blame game: that failure is not the developer's fault.
   
   But if a developer tries to `find` a transaction that doesn't exist, they are actually making a mistake. This time, it _is_ the developer's fault, and we should raise an error. You'll notice that [`Transaction.void` behaves the same way](https://developers.braintreepayments.com/reference/request/transaction/void/ruby)—it raises an error if you try to void a nonexistent transaction.

2. You're absolutely right about the second point and we're fixing our docs right now. We'll close this issue when that part is fixed.

**Comment by dan-ding** [comment] 2017-05-22 22:28
Well
I'd agree with you on (1) that there is an error - but blaming I'm not so sure about as a tactic as it seems washable (how can one know whether something exists without looking for it?). And as well what you have here is just as `ActiveRecord` itself behaves with the `.find` method (which I also don't like). I don't like like it because its failure response is just the oppose of a `.find_by` method which returns nil and `.find_by!` raises the not found error. To me, this is odd when `.find` is really just a focused `.find_by` (not by way of code, but by logic).
I would also argue that `Transaction.void`, should be `.void!`, and `.sale` could have a (or be) `.sale!`  for the similar reasons. By having the choice between non-bang and bang methods - we allow the developer to chose how to code (yes, with AR, one could use a find_by instead of a find, however we don't have that choice here).
Not-withstanding any of the above, I understand where you are coming from - do as you will!

And thanks for (2)!

**Comment by crookedneighbor** [comment] 2017-09-18 20:13
Thanks for the feedback. At this time, we're going to leave the methods as they are, so I'm going to close this issue.

**Closed by crookedneighbor** 2017-09-18 20:13 UTC
