### ISSUE TITLE
Cannot load gem / initialise Rails app after 2.79 upgrade

### ISSUE THREAD

**Issue by januszm** [braintree/braintree_ruby#153] opened 2017-11-21 20:12 UTC
### General information

* SDK/Library version: 2.79
* Environment: Production
* Language, language version, and OS: Ruby 2.4.2 MRI, Mac OS X 10.11

### Issue description

I just upgraded gem `braintree` to version 2.79 via `bundle update` without touching the rest of the code and it can't precompile the assets, with the following error:

```ruby
+ su -s /bin/bash -c 'bundle exec /opt/elasticbeanstalk/support/scripts/check-for-rake-task.rb assets:precompile' webapp
...
NameError: uninitialized constant Braintree
  /var/app/ondeck/config/initializers/braintree.rb:1
...
rake aborted!
```

No issues with version 2.78. It seems that it's related to file permissions which are set to 0600 instead of 0644 for files, at least on AWS platform. Gem cannot be loaded by a user different from the one who installed it.

**Comment by crookedneighbor** [comment] 2017-11-21 20:16
Nothing is jumping out at me for the diff between 2.78.0 and 2.79.0. What was the previous version of the Gem you were using? Was it 2.78.0 or an earlier version?

**Comment by januszm** [comment] 2017-11-21 20:22
Previous version was `2.78`. I do regular, frequent gem updates.

I first noticed it today when I did `bundle update` and then tried to deploy the app to the staging env, which uses RAILS_ENV `production`, but BRAINTREE_ENV `sandbox`

**Comment by crookedneighbor** [comment] 2017-11-21 20:30
Took a second look [at the diff](https://github.com/braintree/braintree_ruby/compare/2.78.0...2.79.0), and I still don't see any changes that look like it would have caused this.

Was Braintree the only gem you updated, or did you update other gems as well? What does your Braintree config look like? (with private keys censored, of course)

**Comment by januszm** [comment] 2017-11-21 20:40
```ruby
Braintree::Configuration.environment = ENV['BRAINTREE_ENV']  # sandbox
Braintree::Configuration.merchant_id = ENV['BRAINTREE_MERCHANT_ID']
Braintree::Configuration.public_key = ENV['BRAINTREE_PUBLIC_KEY']
Braintree::Configuration.private_key = ENV['BRAINTREE_PRIVATE_KEY']
```
I will work on debugging this tomorrow.

**Comment by januszm** [comment] 2017-11-22 11:30
@crookedneighbor I updated the issue description.
I'll close it, this looks more like a platform (Amazon Elastic Beanstalk) related issue.

For some reason the app cannot see the new version of the gem during deployment nor when I try to run the `rails console` (`LoadError: cannot load such file -- braintree`).


Gem is installed of course.
```
$ bundle show braintree
/opt/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/braintree-2.79.0
$ bundle exec irb
irb(main):001:0> require 'braintree'
LoadError: cannot load such file -- braintree
```

**Comment by superp** [comment] 2017-11-22 11:32
I have the same trouble in production mode after update to 2.79 version. Ruby 2.3.3
But error is: 
`cannot load such file -- braintree (LoadError)`

When downgrade to 2.78, it works fine.

**Comment by superp** [comment] 2017-11-22 11:35
@januszm Can you reopen issue?

**Comment by januszm** [comment] 2017-11-22 11:38
@crookedneighbor here was the problem.

```
$ ls -la /opt/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/braintree-2.79.0/lib/
total 24
drwxr-xr-x 4 root root 4096 Nov 22 11:29 .
drwxr-xr-x 4 root root 4096 Nov 22 11:29 ..
drwxr-xr-x 9 root root 4096 Nov 22 11:29 braintree
-rw------- 1 root root 5839 Nov 22 11:29 braintree.rb
```

app runs as `webapp` user and for some reason this installation sets access rights to 0600, not 0644 as for other gems

**Comment by januszm** [comment] 2017-11-22 11:39
@superp please take a look at my last comment and updated description

**Comment by crookedneighbor** [comment] 2017-11-22 14:00
Thanks for the info. We'll look into this today.

**Comment by crookedneighbor** [comment] 2017-11-22 22:16
When we did the 2.79.0 release, some tooling changed and it caused it to be released with the wrong permissions. We've updated the tooling to have the correct permissions and released v2.80.0. Could you try updating to that version?

Thanks for your patience.

**Comment by erkie** [comment] 2017-11-23 15:56
I upgraded seconds ago to 2-80.0 and am getting a new error:

```
Message from application: cannot load such file -- braintree/ach_mandate (LoadError)
  /usr/local/rvm/gems/ruby-2.4.1/gems/braintree-2.80.0/lib/braintree.rb:24:in `require'
  /usr/local/rvm/gems/ruby-2.4.1/gems/braintree-2.80.0/lib/braintree.rb:24:in `<top (required)>'
  /home/app/feeder/config/application.rb:5:in `require'
  /home/app/feeder/config/application.rb:5:in `<top (required)>'
  /home/app/feeder/config/environment.rb:2:in `require_relative'
  /home/app/feeder/config/environment.rb:2:in `<top (required)>'
  config.ru:4:in `require_relative'
  config.ru:4:in `block in <main>'
```

**Comment by johanrothoff** [comment] 2017-11-23 16:04
Great work Erik! Smashing fix.

**Comment by januszm** [comment] 2017-11-24 12:58
Also, It feels like those changes are rather bugfixes/patches than features, and should be released with the tiny version bumps (2.79.1 ...)

**Comment by crookedneighbor** [comment] 2017-11-24 20:38
We had other things go out with the 2.80.0 release than just the permissions issue.

@januszm are you still experiencing issues running 2.80.0, or are you resolved now?

@erkie We'll try to reproduce your issue on Monday.

**Comment by crookedneighbor** [comment] 2017-11-27 18:08
@erkie I cannot reproduce the issue using Passenger on Mac OS. Can you provide a code snippet or git repo that _can_ reproduce the issue?

@januszm Can you confirm if the problem is resolved for you?

**Comment by januszm** [comment] 2017-11-27 19:42
@crookedneighbor I can confirm that 2.80.0 has permissions set properly for the most important, `lib` directory. However, access rights to LICENSE and README.rdoc are still set to 0600. It's not causing any problems with deployments though, it seems that we can close this issue.

```bash
[root@ip-172-31-34-15 current]# ls -la /opt/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/braintree-2.80.0
total 28
drwxr-xr-x   4 root root 4096 Nov 27 19:27 .
drwxr-xr-x 124 root root 4096 Nov 27 19:27 ..
-rw-r--r--   1 root root  628 Nov 27 19:27 braintree.gemspec
drwxr-xr-x   4 root root 4096 Nov 27 19:27 lib
-rw-------   1 root root 1086 Nov 27 19:27 LICENSE
-rw-------   1 root root 3634 Nov 27 19:27 README.rdoc
drwxr-xr-x   8 root root 4096 Nov 27 19:27 spec
[root@ip-172-31-34-15 current]# ls -la /opt/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/braintree-2.80.0/lib/
total 24
drwxr-xr-x 4 root root 4096 Nov 27 19:27 .
drwxr-xr-x 4 root root 4096 Nov 27 19:27 ..
drwxr-xr-x 9 root root 4096 Nov 27 19:27 braintree
-rw-r--r-- 1 root root 5868 Nov 27 19:27 braintree.rb
drwxr-xr-x 2 root root 4096 Nov 27 19:27 ssl
```

I'm just curious, what tooling causes those troubles? How do you guys publish this gem to rubygems.org?

**Comment by crookedneighbor** [comment] 2017-11-27 20:16
The actual packaging and publishing is just a normal:

```
gem build braintree.gemspec
gem push braintree-version-here.gem
```

But what we learned last week is that the umask permissions for building the gem are inherited from the box that built it. 

Our infrastructure team made some changes to the default umask settings on our development boxes, and that caused these permissions changes. (that's why pointing to github, which _does not_ inherit those permissions settings, worked)

Gonna see if we can alter our deploy process to fix the restrictive permissions for the license and readme files as well.

I'm going to close this since the original issue is resolved. @erkie if you're still having issues, please reach out to our support team at https://developers.braintreepayments.com/forms/contact

**Comment by erkie** [comment] 2017-11-27 20:54
No, not sure why you closed this issue. The error I'm seeing is exactly the same, and related to exactly the same version as mentioned by the issue.

As per your request here is a minimal project to reproduce.
https://github.com/erkie/braintree_broke 

```
App 65 stdout:
[ 2017-11-27 20:50:51.7465 30/7f81483dd700 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /home/app: An error occurred while starting up the preloader.
  Error ID: 8d58feb0
  Error details saved to: /tmp/passenger-error-dZM9qV.html
  Message from application: cannot load such file -- braintree/ach_mandate (LoadError)
  /usr/local/rvm/gems/ruby-2.4.1/gems/braintree-2.80.0/lib/braintree.rb:24:in `require'
  /usr/local/rvm/gems/ruby-2.4.1/gems/braintree-2.80.0/lib/braintree.rb:24:in `<top (required)>'
  /usr/local/rvm/gems/ruby-2.4.1@global/gems/bundler-1.15.1/lib/bundler/runtime.rb:82:in `require'
  /usr/local/rvm/gems/ruby-2.4.1@global/gems/bundler-1.15.1/lib/bundler/runtime.rb:82:in `block (2 levels) in require'
  /usr/local/rvm/gems/ruby-2.4.1@global/gems/bundler-1.15.1/lib/bundler/runtime.rb:77:in `each'
  /usr/local/rvm/gems/ruby-2.4.1@global/gems/bundler-1.15.1/lib/bundler/runtime.rb:77:in `block in require'
  /usr/local/rvm/gems/ruby-2.4.1@global/gems/bundler-1.15.1/lib/bundler/runtime.rb:66:in `each'
  /usr/local/rvm/gems/ruby-2.4.1@global/gems/bundler-1.15.1/lib/bundler/runtime.rb:66:in `require'
  /usr/local/rvm/gems/ruby-2.4.1@global/gems/bundler-1.15.1/lib/bundler.rb:108:in `require'
  /home/app/config/application.rb:7:in `<top (required)>'
  /home/app/config/environment.rb:2:in `require_relative'
  /home/app/config/environment.rb:2:in `<top (required)>'
  config.ru:3:in `require_relative'
  config.ru:3:in `block in <main>'
  /usr/local/rvm/gems/ruby-2.4.1@global/gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'
  /usr/local/rvm/gems/ruby-2.4.1@global/gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `eval'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
```

**Comment by erkie** [comment] 2017-11-27 21:07
And here is what I guess is the permissions issue you mentioned:

```
root@896c0f168873:/usr/local/rvm/gems/ruby-2.4.1/gems/braintree-2.80.0/lib/braintree# ls -lah .
total 572K
drwxrwsr-x 9 root rvm 4.0K Nov 27 20:48 .
drwxrwsr-x 4 root rvm 4.0K Nov 27 20:48 ..
-rw-r--r-- 1 root rvm  411 Nov 27 20:48 account_updater_daily_report.rb
-rw------- 1 root rvm  300 Nov 27 20:48 ach_mandate.rb
-rw-r--r-- 1 root rvm  429 Nov 27 20:48 add_on_gateway.rb
-rw-r--r-- 1 root rvm  121 Nov 27 20:48 add_on.rb
drwxrwsr-x 2 root rvm 4.0K Nov 27 20:48 address
-rw-r--r-- 1 root rvm 3.2K Nov 27 20:48 address_gateway.rb
-rw-r--r-- 1 root rvm 2.4K Nov 27 20:48 address.rb
-rw-r--r-- 1 root rvm 3.6K Nov 27 20:48 advanced_search.rb
-rw-r--r-- 1 root rvm  733 Nov 27 20:48 amex_express_checkout_card.rb
-rw-r--r-- 1 root rvm  878 Nov 27 20:48 android_pay_card.rb
-rw------- 1 root rvm  964 Nov 27 20:48 apple_pay_card.rb
-rw------- 1 root rvm 1.3K Nov 27 20:48 apple_pay_gateway.rb
-rw------- 1 root rvm  324 Nov 27 20:48 apple_pay_options.rb
-rw------- 1 root rvm  618 Nov 27 20:48 apple_pay.rb
-rw------- 1 root rvm  383 Nov 27 20:48 authorization_adjustment.rb
-rw-r--r-- 1 root rvm  818 Nov 27 20:48 base_module.rb
```

(note `ach_mandate.rb` which was mentioned in the exception above)

**Comment by januszm** [comment] 2017-11-27 21:16
yep, indeed there's still plenty of files with 0600 permissions. I just did a test deployment to my staging server and didn't see the error, but I'm not going to use this version in production yet.

```
-rw------- 1 root root   300 Nov 27 19:27 ach_mandate.rb
-rw------- 1 root root   964 Nov 27 19:27 apple_pay_card.rb
-rw------- 1 root root  1273 Nov 27 19:27 apple_pay_gateway.rb
-rw------- 1 root root   324 Nov 27 19:27 apple_pay_options.rb
-rw------- 1 root root   618 Nov 27 19:27 apple_pay.rb
-rw------- 1 root root   383 Nov 27 19:27 authorization_adjustment.rb
-rw------- 1 root root   375 Nov 27 19:27 connected_merchant_paypal_status_changed.rb
-rw------- 1 root root   374 Nov 27 19:27 connected_merchant_status_transitioned.rb
-rw------- 1 root root  8383 Nov 27 19:27 credit_card.rb
-rw------- 1 root root  2118 Nov 27 19:27 credit_card_verification.rb
-rw------- 1 root root  8007 Nov 27 19:27 customer.rb
-rw------- 1 root root  5428 Nov 27 19:27 dispute_gateway.rb
-rw------- 1 root root  3739 Nov 27 19:27 dispute.rb
-rw------- 1 root root   785 Nov 27 19:27 dispute_search.rb
-rw------- 1 root root  1007 Nov 27 19:27 document_upload_gateway.rb
-rw------- 1 root root   789 Nov 27 19:27 document_upload.rb
-rw------- 1 root root   527 Nov 27 19:27 facilitated_details.rb
-rw------- 1 root root  2116 Nov 27 19:27 gateway.rb
-rw------- 1 root root  6728 Nov 27 19:27 http.rb
-rw------- 1 root root   612 Nov 27 19:27 ideal_payment_gateway.rb
-rw------- 1 root root  1398 Nov 27 19:27 ideal_payment.rb
-rw------- 1 root root  2205 Nov 27 19:27 masterpass_card.rb
-rw------- 1 root root  4602 Nov 27 19:27 merchant_account_gateway.rb
-rw------- 1 root root  1223 Nov 27 19:27 merchant_gateway.rb
-rw------- 1 root root   711 Nov 27 19:27 merchant.rb
-rw------- 1 root root   493 Nov 27 19:27 paginated_collection.rb
-rw------- 1 root root   304 Nov 27 19:27 paginated_result.rb
-rw------- 1 root root   480 Nov 27 19:27 payment_instrument_type.rb
-rw------- 1 root root   704 Nov 27 19:27 payment_method.rb
-rw------- 1 root root   798 Nov 27 19:27 successful_result.rb
-rw------- 1 root root  1076 Nov 27 19:27 us_bank_account.rb
-rw------- 1 root root  4315 Nov 27 19:27 util.rb
-rw------- 1 root root  2338 Nov 27 19:27 visa_checkout_card.rb
-rw------- 1 root root 465 Nov 27 19:27 evidence.rb
-rw------- 1 root root 284 Nov 27 19:27 history_event.rb
-rw------- 1 root root 437 Nov 27 19:27 transaction.rb
-rw------- 1 root root 2456 Nov 27 19:27 credit_card.rb
-rw------- 1 root root 3497 Nov 27 19:27 nonce.rb
-rw------- 1 root root 1216 Nov 27 19:27 credit_card_details.rb
-rw------- 1 root root  331 Nov 27 19:27 ideal_payment_details.rb
-rw------- 1 root root 1115 Nov 27 19:27 masterpass_card_details.rb
-rw------- 1 root root  561 Nov 27 19:27 paypal_details.rb
-rw------- 1 root root  464 Nov 27 19:27 us_bank_account_details.rb
-rw------- 1 root root 1137 Nov 27 19:27 visa_checkout_card_details.rb
-rw------- 1 root root 3669 Nov 27 19:27 generator.rb
```
+ few in test and xml folders.

**Comment by crookedneighbor** [comment] 2017-11-27 21:17
We're going to work on getting out a new version this week. Thanks for your patience and assistance with this.

**Comment by crookedneighbor** [comment] 2017-11-27 22:46
We've just released 2.80.1, which should have all the permissions fixed. Turns out that the process the gem command uses to build the gem uses the current `umask` value for some things, and the current permissions of the files and directories for other things.

It _should_ be resolved now in v2.80.1.

@januszm @erkie could you verify that the issue is resolved for you?

I ran the sample app provided by @erkie with 2.80.1 and no longer get the braintree permissions issue.

**Comment by crookedneighbor** [comment] 2017-11-29 13:13
I'm fairly certain that the issue is resolved now, but if y'all are still having issues, feel free to comment here and we'll continue to investigate.

**Closed by crookedneighbor** 2017-11-29 13:13 UTC

**Comment by erkie** [comment] 2017-11-30 08:36
We're running the latest in production now so all good. Thanks for the help!
